version: 0.0
os: linux

files:
  - source: dist/ecommerce
    destination: /var/www/html/angular-app
    overwrite: yes

  - source: dist/ecommerce/nginx.conf
    destination: /etc/nginx/
    overwrite: yes

permissions:
  - object: /var/www/html/angular-app
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: root






