version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js 16"
      - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      - sudo apt install -y nodejs
      - node -v
      - npm -v
      - echo "Cleaning up old dependencies..."
      - rm -rf node_modules package-lock.json
      - npm cache clean --force
      - echo "Installing Angular CLI"
      - npm install -g @angular/cli@15.2.6
      - echo "Installing project dependencies"
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo "Building Angular project..."
      - ng build --configuration=production

  post_build:
    commands:
      - echo "Uploading build artifacts..."
      - aws s3 cp dist/shubh/ s3://angular-eapp/angular-folder/ --recursive

artifacts:
  files:
    - '**/*'
  base-directory: dist/shubh/


   

