version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js"
      - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      - sudo apt install -y nodejs
      - node -v
      - echo "Installing Angular CLI"
      - npm install -g @angular/cli@15.2.6
      - npm install  # Install project dependencies

  build:
    commands:
      - echo "Building Angular project"
      - ng build --configuration=production  # Build for production

  post_build:
    commands:
      - echo "Uploading build artifacts to S3..."
      - aws s3 cp dist/your-angular-project-name/ s3://your-s3-bucket-name/angular-folder/ --recursive
      - echo "Creating deployment package"
      - mkdir -p deploy
      - cp -r dist/your-angular-project-name/* deploy/
      - zip -r deploy.zip deploy/
      - echo "Uploading deployment package to S3"
      - aws s3 cp deploy.zip s3://angular-eapp/angular-folder/deploy.zip

artifacts:
  files:
    - deploy.zip
  discard-paths: yes

