version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js 16..."
      - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      - sudo apt install -y nodejs
      - node -v
      - npm -v
      - echo "Installing Angular CLI..."
      - npm install -g @angular/cli@15.2.6
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo "Building Angular project..."
      - ng build --configuration=production

  post_build:
    commands:
      - echo "Ensuring appspec.yml is included..."
      - cp appspec.yml dist/ecommerce/  # Move appspec.yml to dist/ecommerce
      - echo "Uploading build artifacts to S3..."
      - aws s3 cp dist/ecommerce/ s3://angular-eapp/angular-folder/ --recursive
      - aws s3 cp appspec.yml s3://angular-eapp/angular-folder/appspec.yml  # Ensure appspec.yml is in S3

artifacts:
  files:
    - appspec.yml 
    - scripts/start.sh   # Include appspec.yml
    - "**/*"
  base-directory: dist/ecommerce/  # Ensure dist/ecommerce is the base directory




   

