version: 0.2

phases:
  install:
    commands:
      - echo "Checking Node version"
      - node -v
      - echo "Installing Angular CLI"
      - npm install -g @angular/cli
      - echo "Running npm install"
      - npm install
  build:
    commands:
      - echo "Building Angular project"
      - ng build --prod
  post_build:
    commands:
      - echo "Uploading build artifacts to S3..."
      - aws s3 cp dist/your-angular-project-name/ s3://angular-eapp/angular-folder/ --recursive

artifacts:
  files:
    - '**/*'
  base-directory: dist/your-angular-project-name
  discard-paths: yes
