version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js..."
      - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      - sudo apt install -y nodejs
      - npm install -g @angular/cli@15.2.6
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo "Building Angular project..."
      - ng build --configuration=production

  post_build:
    commands:
      - echo "Copying appspec.yml to build directory..."
      - cp appspec.yml dist/ecommerce/
      - echo "Uploading build artifacts to S3..."
      - aws s3 cp . s3://angular-eapp/angular-folder/ --recursive

artifacts:
  files:
    - "**/*"  # Ensures package.json is included
  base-directory: .





   

